### ISSUE TITLE
Error after installing requirements.txt file

### ISSUE THREAD

**Issue by Shrimad-Bhagwat** [Abhishek-Gawade-programmer/socialfly-instagram-clone#24]
### There are errors after installing all the packages from the requirements file.
The requirements.txt file should also contain 
- webpush

      pip install django-webpush

- dotenv

      python -m pip install python-dotenv

**Comment by Abhishek-Gawade-programmer** [comment]
Things are sorted in devlop branch I will Merge it to master as it deployed successfully..
